[project]
name = "orders"
version = "0.1.0"
description = "Orders service"
requires-python = ">=3.8"
dependencies = [
	"fastapi",
	"requests",
	"pyjwt",
<<<<<<< HEAD
=======
	"uvicorn",
>>>>>>> 7d7988b (add uvicorn and init devservers per service)
]

