services:
  books:
    build:
      context: ./books/
      dockerfile: Dockerfile
    image: books:latest
    container_name: books
    restart: always
    environment:
      - PORT=2137
    ports:
      - "2137:2137"

  orders:
    build:
      context: ./orders/
      dockerfile: Dockerfile
    image: orders:latest
    container_name: orders
    restart: always
    environment:
      - PORT=1337
    ports:
      - "1337:1337"

  users:
    build:
      context: ./users/
      dockerfile: Dockerfile
    image: users:latest
    container_name: users
    restart: always
    environment:
      - PORT=6969
    ports:
      - "6969:6969"
