services:
  books:
    build:
      context: ./books/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wdai
    ports:
      - "2137:3000"
    depends_on:
      - db

  orders:
    build:
      context: ./orders/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wdai
    ports:
      - "1337:3000"
    depends_on:
      - db

  users:
    build:
      context: ./users/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wdai
    ports:
      - "6969:3000"
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  
volumes:
  db-data: {}
